plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
    id "com.android.library"
    alias(libs.plugins.compose)
    alias(libs.plugins.kt.compose)
}

apply from: "$mppJvmJsAndroidWithCompose"

android {
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api project(":wishlist.features.common.client")
                api project(":wishlist.features.ui.topBar")
                api project(":wishlist.features.users.client")
                api project(":wishlist.features.auth.client")
                api project(":wishlist.features.email.client")
                api project(":wishlist.features.admin.client")
                api project(":wishlist.features.files.client")
                api project(":wishlist.features.roles.client")
            }
        }
        jsTest {
            dependencies {
                implementation devNpm("jsdom", "26.1.0")
            }
        }
    }
}

tasks.named("jsNodeTest") {
    filter.excludeTestsMatching("dev.inmo.wishlist.features.ui.users.ui.PasswordChangeViewBrowserTest")
    filter.excludeTestsMatching("dev.inmo.wishlist.features.ui.users.ui.UserEditViewBrowserTest")
}
