plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
}

apply from: "$mppJavaProject"

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api project(":wishlist.features.email.common")
                api project(":wishlist.features.common.server")
                api project(":wishlist.features.users.common")
                api project(":wishlist.features.auth.server")
                api project(":wishlist.features.roles.server")
                api project(":wishlist.features.deeplinks.common")
                api project(":wishlist.features.deeplinks.server")
                api libs.angus.mail
            }
        }
        commonTest {
            dependencies {
                implementation libs.ktor.server.test.host
            }
        }
    }
}
