package dev.inmo.wishlist.browser

import com.microsoft.playwright.Browser
import com.microsoft.playwright.BrowserContext
import com.microsoft.playwright.BrowserType
import com.microsoft.playwright.Page
import com.microsoft.playwright.Playwright
import com.microsoft.playwright.Tracing
import com.microsoft.playwright.options.ScreenshotType
import java.nio.file.Files
import java.nio.file.Path

/** Supplies a managed Chromium page and failure diagnostics for served-browser smoke tests. */
internal class BrowserFixture {
    /** Base URL generated by the Gradle browser gate. */
    val baseUrl: String = requiredProperty("browser.baseUrl")
    private val artifactsDirectory: Path = Path.of(requiredProperty("browser.artifactsDir"))
    private val headed: Boolean = System.getProperty("browser.headed", "false").toBoolean()
    private val playwright: Playwright = Playwright.create()
    private val browser: Browser = playwright.chromium().launch(BrowserType.LaunchOptions().setHeadless(!headed))

    /** Creates a fresh unauthenticated context for one test. */
    fun newContext(): BrowserContext = browser.newContext().also {
        it.tracing().start(Tracing.StartOptions().setScreenshots(true).setSnapshots(true).setSources(true))
    }

    /** Saves trace and screenshot diagnostics without replacing the original test failure. */
    fun captureFailure(context: BrowserContext, page: Page, testName: String) {
        val directory = artifactsDirectory.resolve(testName)
        Files.createDirectories(directory)
        runCatching { page.screenshot(Page.ScreenshotOptions().setPath(directory.resolve("failure.png")).setType(ScreenshotType.PNG).setFullPage(true)) }
        runCatching { context.tracing().stop(Tracing.StopOptions().setPath(directory.resolve("trace.zip"))) }
    }

    /** Releases browser resources after the suite. */
    fun close() {
        browser.close()
        playwright.close()
    }

    private fun requiredProperty(name: String): String = requireNotNull(System.getProperty(name)) {
        "$name is missing. Run ./gradlew browserTest so Gradle can prepare the isolated server."
    }
}
