plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
    id "com.android.library"
}

apply from: "$mppJvmJsAndroid"

kotlin {
    sourceSets {
        jvmTest {
            dependencies {
                implementation libs.psql
                implementation libs.xerial.sql
            }
        }
        commonMain {
            dependencies {
                api project(":wishlist.features.common.common")
            }
        }
    }
}