plugins {
    id "org.jetbrains.kotlin.jvm"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    testImplementation libs.playwright
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

tasks.named("test", Test) {
    useJUnitPlatform()
    maxParallelForks = 1
    outputs.upToDateWhen { false }
}
