plugins {
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
    id "com.android.kotlin.multiplatform.library"
    alias(libs.plugins.compose)
    alias(libs.plugins.kt.compose)
}

apply from: "$mppJvmJsAndroidWithCompose"

android {
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

kotlin {
    sourceSets {
        commonMain {
            dependencies {
                api project(":wishlist.features.auth.common")
                api project(":wishlist.features.common.client")
                api libs.ktor.client.auth
            }
        }
        commonTest {
            dependencies {
                implementation libs.ktor.client.mock
            }
        }
    }
}
